#! /bin/sh

sxhkd &
panel &
#pkill yabar
#yabar &
###############
pkill compton
compton -b --config ~/.config/compton-i3.conf &
###############
#pkill polybar
#$HOME/.config/polybar/launch.sh
feh --bg-scale feh --bg-scale /home/lubomir/Pictures/backgrounds/f29.png &
#nitrogen --restore &
###############
pkill start-pulseaudio-x11
start-pulseaudio-x11 &
###############
pkill gnome-settings-daemon
gnome-settings-daemon &
setxkbmap -layout "us,sk(qwerty),cz(qwerty)" -option grp:alt_shift_toggle &
pulseaudio -k &
###############
pkill redshift
redshift -l 49:18 &
#sh /home/lubomir/.scripts/conky-startup.sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
numlockx on &

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 1 2 3 4 5 6 7 8 9
#bspc monitor -d          

bspc config border_width         2
bspc config window_gap          18

bspc config focused_sticky_border_color     "#FFB600"
bspc config focused_border_color            "#5D7DFB"
bspc config normal_border_color             "#464646"
bspc config urgent_border_color             "#red"
bspc config active_border_color             "#magenta"
bspc config presel_feedback_color           "#00FFE984"
bspc config window_gap                      "#bspwm_window_gap"


# bspc config top_padding			-5
# bspc config right_padding		0
# bspc config bottom_padding		0
# bspc config left_padding		0

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# RULES

bspc rule -a '*:zathura' state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
#bspc rule -a libreoffice-writer state=tiled
bspc rule -a libreoffice-writer desktop=^3
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config external_rules_command sh ~/.scripts/bspwm/windows_rules.sh
