#! /bin/sh

sxhkd &
#panel &
compton -b --config ~/.config/compton-i3.conf &
sh ~/.config/polybar/launch.sh
feh --bg-scale feh --bg-scale /home/lubomir/Pictures/backgrounds/airslate-graphite-1.jpg &
#nitrogen --restore &
start-pulseaudio-x11 &
gnome-settings-daemon &
setxkbmap -layout "us,sk(qwerty),cz(qwerty)" -option grp:alt_shift_toggle &
pulseaudio -k &
redshift -l 49:18 &
sh /home/lubomir/.scripts/conky-startup.sh
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &
numlockx on &

bspc monitor -d I II III IV V VI
#bspc monitor -d          

bspc config border_width         2
bspc config window_gap          20

bspc config focused_sticky_border_color     "#FFB600"
bspc config focused_border_color            "#5D7DFB"
bspc config normal_border_color             "#464646"
bspc config urgent_border_color             "#red"
bspc config active_border_color             "#magenta"
bspc config presel_feedback_color           "#00FFE984"
bspc config window_gap                      "#bspwm_window_gap"


bspc config top_padding 25
bspc config right_padding 0
bspc config bottom_padding 0
bspc config left_padding 0

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

# RULES

bspc rule -a '*:zathura' state=tiled
bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
