#!/usr/bin/env bash

################################################################################
#
# CUSTOM PLUGIN SECTION
#
################################################################################

############################################################
# Variables
############################################################

###
### Custom Defines
###
appname="cputemp"
core="${BLOCK_INSTANCE:-Core 0}"
format=" {temp}°C"


###
### Thresholds
###

# Enable
has_threshold=1

# Depending on the conditions in your custom_action()
# you can force the output to be critical or warning
# Set these vars to 1 (in custom_action)
force_crit=0
force_warn=0
force_good=0


###
### Additional arguments
###
arg_params=(
	"-c"
)
arg_vars=(
	"core"
)
arg_desc_val=(
	"<core>"
)
arg_desc_long=(
	"Specify the core name being used by 'sensors'. This can also be set via i3blocks 'instance=' value. If neither is set, it will default to 'Core 0'."
)


###
### Format placeholders
###

# bash variable names
format_vars=(
	temp
)

# Format placeholders
format_nodes=(
	"{temp}"
)

# Format description (for help display)
format_descs=(
	"Temperature"
)

# Format examples (for help display)
format_examples=(
	"-f \" {temp}°C\""
)


############################################################
# custom_actio function
############################################################

###
### Evaluate disk space
###
custom_action() {
	if ! command -v sensors > /dev/null 2>&1; then
		echo "Error, binary 'sensos' not installed, but required for this module to work."
		echo "Type '${appname} -h' for help"
		exit 1
	fi
	temp="$( sensors | grep "${core}" | grep -oE '[.0-9]*°C' | head -1 | grep -oE '[0-9]*'| head -1 )"
}
