#!/bin/bash

STATUS=$(mocp -i | grep "State:" | sed -e "s/^.*: //")
TITLE=$(mocp -i | grep "^Title:" | sed -e "s/^.*: //")
ARTIST=$(mocp -i | grep "Artist:" | sed -e "s/^.*: //")
SONGTITLE=$(mocp -i | grep "SongTitle:" | sed -e "s/^.*: //")

#if [[ $STATUS == PLAY ]]; then
# if [[ $TITLE != "" ]]; then
# if [[ $ARTIST != "" ]]; then ARTIST="$ARTIST -"; fi
# echo -e " $ARTIST $SONGTITLE"
# else echo -e " Prehráva sa "
# fi
#fi

if [[ $STATUS == PLAY ]]; then
 echo -e "  Prehráva sa "
fi

if [[ $STATUS == PAUSE ]]; then
 echo -e "  Pozastavené "
fi

case $BLOCK_BUTTON in
 1) mocp -f ;; # left click = next song
 2) mocp -G ;; # middle click = toggle pause - play
 3) mocp -r ;; # right click = previous song
esac
exit 0

if [[ ! -z $(pidof mocp) ]] &>/dev/null 2>&1; then
 echo -e " "
else echo -e " "
fi
